'use strict';
// Problem knowledge for every trade the engineers cover. Each row says what the item and symptom look like in a
// technician's words, and the steps of the work. The same steps are written as a to-do for the WORQ request and in
// past tense for the closing comment, so write each step as one verb phrase (imperative) separated by "|".

const IRREGULAR = { find: 'found', take: 'took', let: 'let', keep: 'kept', shut: 'shut', cut: 'cut', reset: 'reset', set: 'set', put: 'put', sweep: 'swept', bleed: 'bled', run: 'ran', hold: 'held', build: 'built', rebuild: 'rebuilt', lay: 'laid', 'cut out': 'cut out', 'tear': 'tore', 'dig': 'dug', 'tape': 'taped', 'mud': 'mudded' };
const DOUBLE = new Set(['fit', 'stop', 'plug', 'drop', 'strip', 'tag', 'swap', 'wrap', 'mud', 'tap', 'clip', 'trim', 'rip', 'scrap', 'step', 'pin', 'shim', 'strap', 'grip', 'slip', 'pop']);

function toPast(word) {
  const w = word.toLowerCase();
  if (IRREGULAR[w]) return IRREGULAR[w];
  if (/^[a-z-]*[^aeiou]y$/.test(w)) return w.replace(/y$/, 'ied');
  if (/e$/.test(w)) return `${w}d`;
  if (DOUBLE.has(w)) return `${w}${w[w.length - 1]}ed`;
  return `${w}ed`;
}
// Every verb used in the steps. A step like "clean and dry the joint" has two verbs, and both need the past tense.
const KNOWN_VERBS = new Set(('shut clean tighten replace repair remove install check inspect adjust test confirm lubricate flush clear dry restore cut seal secure reset apply measure mask sand prime paint patch set keep cover smooth sweep thaw insulate isolate treat haul collect monitor correct bleed scrape extract rinse let allow place support reach note protect straighten trace restart find stop fill caulk vacuum return compact label evacuate recharge reconnect balance diagnose lock reseal re-secure re-anchor repoint re-hang re-stretch re-terminate re-level reinstall vacuum fit diagnose identify report coordinate take run spot-treat pre-treat apply turn drain disconnect de-energize document notify').split(' '));
const DET = new Set('the a an any all it them this that these those new each up out off down over in on to with both some proper normal full quiet correct compliant steady cold watertight tight stable level there no'.split(' '));
const ADJECTIVE_LIKE = new Set(['secure', 'open', 'close', 'smooth', 'level', 'clear', 'safe']);   // also adjectives: only converted when a determiner follows
function pastPhrase(act) {
  const toks = act.split(' ');
  toks[0] = toks[0].replace(/^([A-Za-z-]+)/, (m) => toPast(m));
  for (let i = 1; i < toks.length; i++) {
    const prev = toks[i - 1], w = toks[i].replace(/,$/, ''), comma = toks[i].endsWith(',') ? ',' : '';
    const afterList = /^(and|or)$/i.test(prev) || prev.endsWith(',');
    const next = toks[i + 1];
    // convert a following verb only when a determiner or the end comes next, so "smooth, secure operation" is left alone
    const listItem = !!comma || (next !== undefined && /^(and|or)$/i.test(next));          // "inspect, clean or replace ..."
    const followedByObject = next === undefined || DET.has(next.replace(/,$/, '').toLowerCase());
    if (afterList && KNOWN_VERBS.has(w) && (followedByObject || (listItem && !ADJECTIVE_LIKE.has(w)))) toks[i] = toPast(w) + comma;
  }
  return toks.join(' ');
}
const sentenceOf = (acts, past) => {
  const list = acts.map((a) => (past ? pastPhrase(a) : a));
  const first = list[0].charAt(0).toUpperCase() + list[0].slice(1);
  const parts = [first, ...list.slice(1)];
  if (parts.length === 1) return `${parts[0]}.`;
  if (parts.length === 2) return `${parts[0]} and ${parts[1]}.`;
  return `${parts.slice(0, -1).join(', ')}, and ${parts[parts.length - 1]}.`;
};

// R(id, item regex, symptom regex or null, verb for the WORQ, steps "a|b|c", what is typically found, why it matters, extras)
const R = (id, obj, sym, imp, steps, found, why, o = {}) => {
  const acts = steps.split('|');
  return { id, obj, sym, imp, past: toPast(imp), steps: sentenceOf(acts, true), scope: sentenceOf(acts, false), found, why, ...o };
};

const ROOF = { crew: 2, access: 'Roof access required.' };
const LIFT = { crew: 2, access: 'Lift or ladder required.' };

const TRADES = [
  // ---------------- PLUMBING ----------------
  R('shower-clog', /shower|bathtub|\btub\b/i, /clog|slow|backed|won'?t drain|standing water|plug/i, 'clear', 'remove the hair and debris blockage from the drain|flush the line with hot water|confirm the drain flows freely', 'Investigation found the drain blocked with hair and soap buildup.', 'Standing water makes the fixture unusable and can cause odors.'),
  R('flush-valve', /urinal|flush ?valve|flushometer/i, /flush|run|leak|stuck|weak|sensor|hiss|handle|won'?t|not work|broke/i, 'repair', 'inspect the flush valve and sensor|replace the worn diaphragm or failed sensor|adjust the water volume|confirm a full flush and proper shut-off', 'Investigation found a worn diaphragm or failed sensor in the flush valve.', 'The fixture is out of service or wasting water.', { invest: true }),
  R('toilet-loose', /toilet|commode/i, /loose|wobbl|rock|base|shift/i, 'repair', 'shut off the water and remove the toilet|replace the wax ring and mounting bolts|reset and secure the toilet to the floor|confirm there are no leaks at the base', 'Investigation found a failed wax seal and loose mounting bolts.', 'A loose toilet can leak and damage the floor.'),
  R('toilet-seat', /toilet seat/i, null, 'replace', 'remove the damaged seat|install a new seat and tighten the mounting hardware|confirm it is secure', 'Inspection found a cracked or loose seat.', 'A broken seat is unsanitary and unsafe to use.'),
  R('sink-loose', /sink|basin|lavatory|vanity/i, /loose|pull(ing)? away|detach|sag|wobbl|separat/i, 'secure', 'remove the failed mounting clips or brackets|re-anchor the sink to the vanity or wall|re-seal the edges|confirm the sink is firmly secured', 'Inspection found failed mounting hardware.', 'A loose sink can crack, leak or fall.'),
  R('sink-leak', /sink|basin|lavatory|vanity/i, /leak|drip|seep|water (under|below)|wet cabinet/i, 'repair', 'check under the sink to find the source of the leak|tighten or replace the failed supply line, trap or faucet connection|dry the cabinet and the area|run the water and confirm there are no leaks', 'Investigation found a leaking supply line, trap or faucet connection.', 'The leak can damage the cabinet and floor and wastes water.', { invest: true }),
  R('ptrap-leak', /p-?trap|\btrap\b|drain pipe|drain line|supply line|shut-?off valve|angle stop|stop valve|compression fitting/i, /leak|drip|seep|corrod/i, 'repair', 'place a bucket and shut off the water supply|tighten or replace the leaking fitting, washer or valve|restore the water and confirm there are no leaks', 'Investigation found a worn fitting or washer leaking at the connection.', 'The leak can damage the cabinet and floor and wastes water.'),
  R('hose-bib', /hose ?bib|spigot|exterior faucet|outdoor faucet|hydrant|wall hydrant/i, /leak|drip|broke|froze|won'?t shut|spray|handle|stem|run/i, 'repair', 'shut off the water supply|replace the worn stem, washer or entire bib|restore the water and confirm it shuts off fully', 'Investigation found a worn stem or washer.', 'The leak wastes water and can damage the exterior wall or freeze.'),
  R('low-pressure', /water pressure|low pressure|no water|low water|weak water|water flow|poor flow/i, null, 'repair', 'check the main shutoff and the pressure reducing valve|inspect the aerators, strainers and fixtures for restrictions|adjust or replace the failed component|confirm normal pressure at the fixtures', 'Investigation found a restriction or failed pressure component.', 'Low water pressure affects staff and customers and can point to a bigger problem.', { invest: true }),
  R('water-heater-leak', /water heater|hot water tank|boiler tank/i, /leak|drip|rust|puddle|weep|corrod/i, 'repair', 'shut off the power or gas and the water supply|inspect the tank, fittings and relief valve for the source|repair or replace the failed component|restore service and confirm there are no leaks', 'Investigation found a leak at a fitting, the relief valve or the tank.', 'A leaking water heater can cause water damage and loss of hot water.', { invest: true }),
  R('sump', /sump|ejector|lift station|sewage pump/i, null, 'repair', 'inspect the pit and clear debris|test the float switch and pump operation|repair or replace the failed pump or switch|confirm the pit pumps down properly', 'Investigation found a failed pump or stuck float switch.', 'A failed pump can flood the building.', { invest: true }),
  R('sewer', /sewer|sewage|main line|mainline|sewer gas/i, null, 'clear', 'inspect the cleanouts and the main line|clear the blockage with a drain machine|flush the line and confirm normal flow|sanitize the affected area', 'Investigation found a blockage in the main line.', 'A sewage backup is a health hazard and can damage the building.', { invest: true, crew: 2 }),
  R('frozen-pipe', /(frozen|freez\w*|ice).{0,12}(pipe|line|water|sprinkler)|(pipe|line|water|sprinkler).{0,12}(frozen|freez\w*|ice)/i, null, 'repair', 'safely thaw the frozen pipe|inspect for splits or damage|repair any damaged section|insulate or heat-trace the pipe to prevent a repeat|confirm normal flow', 'Investigation found a frozen section of pipe.', 'A frozen pipe can burst and flood the building.', { invest: true }),
  R('backflow', /backflow|rpz|double check/i, null, 'service', 'isolate the assembly|inspect, clean or replace the internal parts|test the assembly|confirm it passes and document the test', 'Inspection found the assembly needing service or testing.', 'Backflow assemblies must pass testing for compliance and to protect the water supply.'),
  R('fountain', /drinking fountain|water fountain|bubbler|water cooler|bottle filler/i, null, 'repair', 'check the water supply and drain|inspect the cooler, valve and filter|replace the failed part|clean the unit and confirm cold, free-flowing water', 'Investigation found a failed valve, filter or cooling component.', 'Drinking water is not available for staff or customers.', { invest: true }),
  R('sensor-faucet', /sensor faucet|automatic faucet|touchless faucet|auto faucet|hands[- ]?free faucet/i, null, 'repair', 'check the battery and sensor|clean or replace the sensor and solenoid|adjust the water temperature and flow|confirm it turns on and shuts off properly', 'Investigation found a dead battery or failed sensor.', 'The faucet does not work, which affects hygiene and customer use.', { invest: true }),

  // ---------------- ELECTRICAL ----------------
  R('emergency-light', /emergency light(ing)?|battery pack|exit sign|exit light|egress light/i, null, 'replace', 'test the unit and check the battery and charging circuit|replace the failed battery, lamp or unit|retest for the required runtime|confirm the indicator light is on', 'Inspection found a failed battery or lamp.', 'Emergency lighting is required for life safety and code compliance.', { invest: true }),
  R('gfci', /gfci|gfi\b|ground fault/i, null, 'repair', 'test and reset the GFCI|check the downstream outlets for faults|replace the failed GFCI device|confirm it trips and resets properly', 'Investigation found a tripped or failed GFCI.', 'The outlet has no power and the protection device must work for safety.', { invest: true }),
  R('breaker', /breaker|panel ?board|electrical panel|load center|disconnect|fuse/i, /trip|won'?t reset|hot|buzz|burn|damag|arc|spark|no power|overload|smell|not work|dead|fail|broke/i, 'repair', 'shut off power and inspect the panel|identify the overloaded or faulty circuit|repair or replace the breaker or wiring|restore power and confirm correct operation', 'Investigation found a faulty breaker or an overloaded circuit.', 'Loss of power affects operations and can be a fire risk.', { invest: true, crew: 2 }),
  R('power-loss', /no power|power (is |was )?out|lost power|power loss|loss of power|outage|dead (area|room|circuit)|power (went|is) down/i, null, 'repair', 'check the breakers, GFCIs and the utility feed|trace and isolate the faulted circuit|repair or replace the failed component|restore power and confirm normal operation', 'Investigation found a tripped protection device or a failed component on the circuit.', 'Loss of power stops equipment and affects operations.', { invest: true, no: /outlet|receptacle|switch|gfci|plug/i }),
  R('light-control', /motion sensor|occupancy sensor|vacancy sensor|photocell|light sensor|lighting control|dimmer|time clock|\btimer\b/i, null, 'repair', 'check the power and settings|clean and adjust the sensor|replace the failed sensor, timer or dimmer|confirm the lights respond properly', 'Investigation found a failed or misadjusted control.', 'The lights do not turn on or off as needed, wasting energy or leaving the area dark.', { invest: true }),
  R('ballast', /ballast|led driver|\bdriver\b/i, /hum|buzz|noise|loud|flicker|out|dead|not work|fail/i, 'replace', 'shut off the power|replace the failed ballast or LED driver|restore power and confirm quiet, steady operation', 'Investigation found a failed ballast or driver.', 'The fixture is noisy or not working, leaving the area under-lit.'),
  R('exposed-wiring', /exposed wir|bare wir|open junction|junction box|cover ?plate|missing cover|conduit|loose wir|wiring/i, /exposed|open|missing|damag|loose|hang|bare|cut|chew|broke|fray/i, 'repair', 'de-energize the circuit|secure and insulate the exposed wiring|install the missing cover or repair the conduit|restore power and confirm it is safe', 'Inspection found exposed or damaged wiring.', 'Exposed wiring is a shock and fire hazard.', { invest: true }),
  R('backup-power', /generator|\bups\b|battery backup|transfer switch|inverter/i, null, 'service', 'inspect the unit, fuel and batteries|run a load test|repair or replace failed components|confirm it starts and transfers properly', 'Inspection found a weak battery or a failed component.', 'Backup power keeps critical systems running during an outage.', { invest: true }),
  R('fire-alarm', /fire alarm|alarm panel|pull station|horn ?strobe|\bstrobe\b|duct detector|annunciator/i, null, 'repair', 'check the panel for trouble signals|inspect and test the affected devices|repair or replace the failed device|reset the panel and confirm a clear status', 'Investigation found a faulty device or wiring fault causing the trouble signal.', 'Life safety equipment must be fully operational.', { invest: true }),
  R('area-light', /(canopy|soffit|drive-?thru|atm|high ?bay|entry|vestibule|walkway|stair(well)?|parking garage|garage) lights?/i, null, 'replace', 'reach the fixtures safely|replace the failed lamps or drivers|check the wiring connections|confirm the lights operate properly', 'Investigation found failed lamps or drivers.', 'The area is under-lit, which affects safety and security.', { invest: true, cond: true, ...LIFT }),
  R('data-jack', /data (jack|outlet|port)|network (jack|port|drop)|phone jack|ethernet|cat ?[56]e?\b|wall jack/i, null, 'repair', 'check the jack and cabling|re-terminate or replace the failed jack|test the connection|label it and confirm connectivity', 'Investigation found a failed jack or cable termination.', 'The connection is down and affects operations.', { invest: true }),
  R('extension-cord', /extension cord|power strip|daisy[- ]?chain|temporary wiring/i, null, 'install', 'remove the unsafe extension cord or power strip|install a permanent outlet or a properly rated circuit|test the circuit|confirm it is safe and tidy', 'Inspection found an extension cord used as permanent wiring.', 'Extension cords used as permanent wiring are a fire and trip hazard.'),

  // ---------------- HVAC ----------------
  R('filter-change', /(?<!water )(?<!oil )filters?/i, /dirty|clog|change|replace|due|restrict|plug|swap|new|clean|needs?/i, 'replace', 'shut down the unit|remove the dirty filters|install new filters of the correct size and rating|restart the unit and confirm proper airflow', 'Inspection found dirty filters restricting airflow.', 'Dirty filters reduce airflow, efficiency and indoor air quality.'),
  R('belt', /\bbelts?\b|pulley|sheave/i, /squeal|loose|worn|crack|broke|slip|nois|fray|snap/i, 'replace', 'lock out the unit|inspect the belt, pulleys and bearings|replace the worn belt and adjust the tension and alignment|restart the unit and confirm quiet, proper operation', 'Inspection found a worn or loose belt.', 'A worn belt reduces airflow and can fail, shutting the unit down.'),
  R('condensate', /condensate|drain pan|primary drain|secondary drain/i, null, 'clear', 'shut down the unit|clear the clogged condensate line and flush it|clean the drain pan and treat it|restart the unit and confirm proper drainage', 'Investigation found the condensate drain clogged with algae and debris.', 'A clogged drain can overflow and damage ceilings and floors.'),
  R('frozen-coil', /(frozen|iced?)( up)?[^.]{0,12}(coil|evaporator|unit|line)|(coil|evaporator)[^.]{0,12}(frozen|ice)/i, null, 'repair', 'shut off cooling and thaw the coil with the fan running|check the filter, airflow and refrigerant charge|correct the cause of the freeze-up|restart the unit and confirm normal operation', 'Investigation found restricted airflow or low refrigerant causing the coil to freeze.', 'A frozen coil stops cooling and can damage the compressor.', { invest: true }),
  R('refrigerant', /refrigerant|freon|low charge|\br-?4\d\d\w?\b/i, null, 'repair', 'check the pressures and locate the leak with detection equipment|repair the leak|evacuate and recharge to specification|confirm proper cooling', 'Investigation found a refrigerant leak.', 'Low refrigerant reduces cooling and can damage the compressor.', { invest: true }),
  R('damper', /damper|\bvav\b|variable air|diffuser|vent\b|register|actuator|economizer|louver/i, /stuck|not work|broke|noisy|won'?t|fail|clos|open|block|rattl|whistl|loose|disconnect/i, 'repair', 'check the damper actuator and the control signal|clean and lubricate the linkage|repair or replace the failed actuator or damper|confirm proper airflow and control', 'Investigation found a stuck damper or a failed actuator.', 'Poor airflow control affects comfort and efficiency.', { invest: true }),
  R('duct', /duct|ductwork|flex ?duct|plenum/i, /leak|damag|disconnect|insulation|torn|crush|sweat|loose|hole|gap|fall|hang|sag/i, 'repair', 'inspect the ductwork and locate the damage|reconnect and seal the joints with mastic or foil tape|replace the damaged sections or insulation|confirm proper airflow and no air leaks', 'Inspection found a disconnected or damaged section of duct.', 'Duct leaks waste energy and reduce comfort.'),
  R('thermostat', /thermostat|\bt-?stat\b/i, /not work|blank|dead|battery|wrong|reading|unrespons|won'?t|replace|set|display|broke|off|temperature|stuck/i, 'replace', 'check the power and batteries|verify the settings and wiring connections|replace or reprogram the thermostat|confirm the unit responds and holds the setpoint', 'Investigation found a dead battery or a failed thermostat.', 'The temperature cannot be controlled, which affects comfort.', { invest: true }),
  R('boiler', /boiler|hydronic|circulator|heating loop|radiant|baseboard heat|radiator|heating pump|hot water loop/i, null, 'repair', 'check the pilot, burner, controls and water pressure|bleed air from the system and inspect the circulator pump|repair or replace the failed component|confirm proper circulation and heat output', 'Investigation found a failed control or circulator.', 'Loss of heat affects comfort and can damage the building in cold weather.', { invest: true }),
  R('chiller', /chiller|cooling tower|condenser water|air[- ]?cooled/i, null, 'service', 'inspect the unit, pumps and controls|check pressures, flows and temperatures|repair or replace the failed component|confirm the system reaches its setpoint', 'Investigation found a fault affecting cooling capacity.', 'Loss of cooling affects comfort and equipment.', { invest: true, crew: 2 }),
  R('mini-split', /mini[- ]?split|ductless|split (unit|system)|server room (ac|a\/c|cooling)|computer room (ac|a\/c|cooling)|crac\b|it room (ac|a\/c|cooling|unit)/i, null, 'repair', 'check the power, thermostat and condensate drain|clean the filters and coils|diagnose and repair the fault|confirm the room reaches and holds the setpoint', 'Investigation found a fault in the cooling unit.', 'Loss of cooling can overheat critical equipment.', { invest: true }),
  R('cold-space', /too cold|freezing in|chilly|cold (room|space|area|office|lobby)|drafty|excessive cold/i, null, 'repair', 'check the thermostat settings and the heating equipment|inspect for drafts, dampers and closed vents|repair the fault or adjust the controls|monitor until the space reaches the setpoint', 'Investigation found a heating or airflow problem in the space.', 'An overly cold space is uncomfortable for staff and customers.', { invest: true, issues: true, fixedSubject: 'cold temperatures' }),
  R('air-quality', /humidity|musty|stuffy|stale air|poor ventilation|poor air/i, null, 'repair', 'check the ventilation rates, dampers and exhaust fans|inspect for moisture sources, leaks or microbial growth|correct the cause|confirm improved air quality and comfort', 'Investigation found inadequate ventilation or a moisture source.', 'Poor air quality affects the comfort and health of staff and customers.', { invest: true }),
  R('rtu-noise', /\brtu\b|rooftop unit|air handler|\bahu\b|fan coil|blower|air handling/i, /nois|loud|vibrat|rattl|squeal|grind|bang|knock|hum/i, 'repair', 'lock out the unit and inspect the fan, motor and bearings|tighten or replace loose, worn or damaged parts|balance and lubricate as needed|restart the unit and confirm quiet, vibration-free operation', 'Investigation found a worn bearing or loose component.', 'The noise points to a failing part that can lead to a breakdown.', { invest: true, ...ROOF }),

  // ---------------- PAINTING & FINISHES ----------------
  R('paint-job', /\b(re-?)?paint(ing)?\b/i, null, 'paint', 'protect the floors and furniture and mask the trim|patch and sand the imperfections and clean the surface|prime where needed|apply two coats of paint to match the existing color|remove the masking and clean up', 'Inspection found the surface needing a fresh coat of paint.', 'Fresh paint keeps the space clean and professional and protects the surface.', { no: /peel|chip|flak|bubbl|stain|scuff|graffiti|water|crack|tile/i }),
  R('wall-crack', /wall|ceiling|drywall|sheetrock/i, /crack|nail pop|screw pop|seam|tape|bulge|settle/i, 'repair', 'cut out the loose material and open the crack|apply mesh tape and joint compound|sand smooth and prime|paint to match the surrounding surface', 'Inspection found a settlement crack or failed joint tape.', 'Cracks look unprofessional and can widen or point to movement.', { no: /tile|hole|water|stain/i }),
  R('wall-water', /wall|ceiling|drywall|sheetrock/i, /water (damage|stain)|stain|mold|moisture|wet|bubbl|leak/i, 'repair', 'find and stop the moisture source|cut out and replace any wet or damaged drywall|prime with a stain-blocking primer|repaint to match', 'Investigation found moisture damage from a leak.', 'Water damage can lead to mold and structural problems.', { invest: true, no: /tile|roof|shingle/i }),
  R('baseboard', /baseboard|cove base|trim|molding|moulding|chair rail|crown/i, /loose|damag|missing|pull|crack|scuff|fall|broke|peel|split/i, 'repair', 'remove the damaged section|cut and fit new base or trim|secure it with adhesive or fasteners|caulk, fill and paint to match', 'Inspection found damaged or loose trim.', 'Damaged trim looks unprofessional and can be a snag hazard.'),
  R('caulk', /caulk|sealant|silicone/i, null, 'caulk', 'remove the old failed caulk|clean and dry the joint|apply new sealant in a smooth bead|let it cure|clean up the work area', 'Inspection found failed or missing sealant.', 'Failed sealant lets in water and looks unprofessional.'),
  R('grout', /grout/i, null, 'repair', 'remove the loose or cracked grout|clean the joints|apply new grout and seal it|clean the tile surface', 'Inspection found cracked or missing grout.', 'Failed grout lets water in and can loosen the tile.'),
  R('carpet-clean', /carpet|rug|mat\b/i, /stain|spill|dirty|odor|smell|soil|wet|gum|dull/i, 'clean', 'pre-treat the stains|extract the carpet with a hot-water cleaner|spot-treat any remaining marks|let it dry|confirm the stains are removed', 'Inspection found stained and soiled carpet.', 'Stained carpet looks unprofessional to customers.'),
  R('carpet-repair', /carpet|rug/i, /rip|torn|fray|buckl|wrinkl|loose|burn|lift|seam|trip/i, 'repair', 'clean and inspect the damaged area|cut out and patch or re-stretch the carpet|secure the edges and seams|vacuum and confirm a smooth, level surface', 'Inspection found torn or buckled carpet.', 'Damaged carpet is a trip hazard and looks unprofessional.'),
  R('floor-finish', /floor|vct|tile|terrazzo|concrete/i, /scuff|dull|wax|strip|buff|dirty|stain|film|streak|scrub/i, 'clean', 'sweep and clean the floor|strip the old finish if needed|apply floor finish evenly in coats|let it dry|return the area to traffic', 'Inspection found worn and scuffed floor finish.', 'A worn floor looks unprofessional and is harder to keep clean.', { no: /carpet|crack|loose|broke|ceiling|wall/i }),
  R('graffiti', /graffiti|\btagging\b|vandal/i, null, 'remove', 'test a small area for surface compatibility|remove the graffiti with the proper cleaner or pressure washing|repaint or seal the surface to match|clean up the area', 'Inspection found graffiti on the surface.', 'Graffiti looks unprofessional and invites more vandalism.', { crew: 2 }),
  R('ceiling-grid', /ceiling grid|t-?bar|suspended ceiling|grid|ceiling (is )?sagging/i, /sag|bent|broke|loose|fall|damag|hang|miss|wire|\bgrid\b/i, 'repair', 'inspect the grid and hangers|re-level and secure or replace the damaged grid|reinstall the tiles|confirm a level, secure ceiling', 'Inspection found a sagging or damaged grid.', 'A sagging ceiling is a safety concern.', { invest: true, no: /tile (water|stain)/i }),
  R('masonry', /brick|masonry|stucco|tuck-?point|mortar|block wall|cmu|\befis\b/i, /crack|loose|missing|spall|crumbl|damag|gap|hole|leak|fall/i, 'repair', 'clean and prepare the damaged area|repoint or patch with matching mortar or stucco|seal and finish to match|clean up the work area', 'Inspection found cracked or deteriorated masonry.', 'Damaged masonry lets in water and can worsen quickly.', LIFT),
  R('exterior-trim', /siding|soffit|fascia|trim board|\beaves?\b|facade|exterior wall/i, /damag|loose|missing|rot|hole|peel|crack|fall|sag|stain|bird|nest/i, 'repair', 'remove the damaged or rotted sections|install new matching material and fasten it securely|caulk, prime and paint to match|inspect the adjacent areas', 'Inspection found damaged or rotted exterior material.', 'Damaged exterior material lets in water and pests.', LIFT),

  // ---------------- DOORS, HARDWARE & GLASS ----------------
  R('door-closer', /door closer|closer\b|door (is )?slamming|slams/i, null, 'adjust', 'inspect the closer arm and mounting|adjust the sweep and latch speeds|tighten or replace the closer|confirm the door closes smoothly and latches', 'Inspection found a closer out of adjustment or leaking.', 'A closer that does not work properly affects security and accessibility.'),
  R('panic-bar', /panic|exit device|crash bar|push bar|rim device|touch bar/i, null, 'repair', 'inspect the exit device, latch and strike|adjust, lubricate or replace the worn components|test for smooth operation from the inside|confirm the door latches securely', 'Inspection found a worn or misadjusted exit device.', 'Exit devices are required for safe egress and must work properly.', { invest: true }),
  R('auto-door', /automatic door|auto door|slider|sliding door|ada (door|operator|button|push)|door operator|push ?button|sensor door|handicap (door|button|operator)|wheelchair/i, null, 'repair', 'check the power, sensors and the operator|clean the sensors and the track|adjust or replace the failed component|test the open and close cycle and the safety sensors', 'Investigation found a dirty sensor or a failed operator component.', 'Automatic doors are needed for accessibility and customer entry.', { invest: true }),
  R('rekey', /re-?key|key copy|new keys?|lost key|change (the )?(lock|core)|locked out/i, null, 'rekey', 'collect the old cores and keys|install and pin new cores to the new key code|test each key|deliver the new keys and log them', 'The locks needed to be rekeyed.', 'Rekeying maintains security after lost keys or personnel changes.'),
  R('hinge', /hinge/i, null, 'repair', 'support the door|tighten, shim or replace the damaged hinges|lubricate the pins|confirm the door swings and closes properly', 'Inspection found loose or damaged hinges.', 'A door with bad hinges can sag, drag and become unsafe.'),
  R('weatherstrip', /weather ?strip|door sweep|threshold|gasket|door seal/i, null, 'replace', 'remove the worn strip, sweep or threshold|install new material and adjust for a tight seal|confirm there are no gaps, drafts or light', 'Inspection found worn or missing weather stripping.', 'Gaps let in air, water and pests and waste energy.'),
  R('overhead-door', /roll[- ]?up|overhead door|dock door|garage door|rolling door|coiling|shutter|dock leveler|loading dock door/i, null, 'repair', 'lock out the opener and inspect the springs, tracks, rollers and opener|lubricate and adjust or replace the worn parts|test the opening, closing and safety reverse|confirm smooth, safe operation', 'Investigation found a worn spring, roller or opener component.', 'The door is a security and safety concern when it does not work properly.', { invest: true, crew: 2 }),
  R('glass', /storefront|glass door|glass panel|plate glass|mirror|glazing|window film|tempered/i, /crack|broke|shatter|chip|scratch|fog|peel|damag|loose|etch/i, 'replace', 'secure and barricade the area|remove the broken glass safely|measure and install replacement glass or film|clean the area and confirm a tight seal', 'Inspection found cracked or broken glass.', 'Broken glass is a safety and security hazard.', { crew: 2, no: /\bsign/i }),
  R('access-control', /card reader|access control|keypad|key ?fob|badge|magnetic lock|mag ?lock|door contact|electric strike|buzzer|intercom/i, null, 'repair', 'check the power, wiring and the reader or lock|test the credential and the door contact|repair or replace the failed device|confirm the door locks, unlocks and logs properly', 'Investigation found a failed reader, lock or power supply.', 'Access control protects the building and must work properly.', { invest: true }),
  R('camera', /camera|cctv|\bdvr\b|\bnvr\b|surveillance/i, null, 'repair', 'check the power and the network connection|clean the lens and adjust the view|replace the failed camera or cable|confirm a clear live image and recording', 'Investigation found a camera with no power or no network connection.', 'Security cameras must be working to protect people and property.', { invest: true }),
  R('night-drop', /night (drop|depository)|drive[- ]?(thru|up) (lane|drawer|tube|window)|pneumatic|tube system/i, null, 'repair', 'inspect the unit, door and mechanism|clear any jams and lubricate the parts|repair or replace the failed part|test several cycles for smooth, secure operation', 'Investigation found a jammed or worn mechanism.', 'The service is unavailable to customers and may be a security concern.', { invest: true }),
  R('door-frame', /door frame|jamb/i, null, 'repair', 'inspect the frame and remove the damaged section|repair or replace the jamb and secure the frame|re-hang or adjust the door|fill, prime and paint to match', 'Inspection found a damaged or loose door frame.', 'A damaged frame affects security and door operation.'),
  R('elevator', /elevator|escalator|dumbwaiter|wheelchair lift/i, null, 'repair', 'take the unit out of service if it is unsafe|report the issue to the elevator service contractor|coordinate the repair and the inspection|confirm safe operation before returning it to service', 'Investigation found a fault that needs the elevator contractor.', 'Vertical transportation is needed for access and safety.', { invest: true }),

  // ---------------- ROOF & EXTERIOR ----------------
  R('roof-drain', /roof drain|scupper|drain strainer|ponding|standing water on (the )?roof|internal drain|overflow drain/i, null, 'clear', 'clear the leaves, debris and sediment from the drains and scuppers|flush the drain lines to confirm they flow|inspect the roof surface and drain flashing|confirm water drains freely', 'Inspection found clogged roof drains and ponding water.', 'Clogged roof drains cause ponding that can lead to leaks and structural damage.', ROOF),
  R('flashing', /flashing|coping|parapet|counterflashing|roof edge|roof curb/i, null, 'repair', 'inspect the flashing and the surrounding membrane|remove loose sealant and clean the surface|re-secure or replace the flashing and reseal|confirm a watertight seal', 'Inspection found loose or failed flashing.', 'Failed flashing is a common source of roof leaks.', ROOF),
  R('membrane', /membrane|\btpo\b|\bepdm\b|modified bitumen|built-?up|roof blister|roof (patch|seam)|roof bubble/i, null, 'patch', 'clean and dry the area|cut out the damaged section|install a membrane patch and heat-weld or adhere it|seal the edges and confirm it is watertight', 'Inspection found a damaged or split roof membrane.', 'A damaged membrane lets water into the building.', ROOF),
  R('skylight', /skylight|roof hatch|roof access hatch|smoke hatch/i, null, 'repair', 'inspect the unit, curb and seals|reseal or replace the damaged parts|check the operation|confirm there are no leaks', 'Inspection found failed seals around the unit.', 'A leaking skylight or hatch lets water into the building.', ROOF),
  R('canopy', /canopy|awning|overhang|drive[- ]?thru cover|portico/i, /damag|loose|bent|leak|torn|rust|sag|crack|fall|hang/i, 'repair', 'secure the area below|inspect the structure and fasteners|repair or replace the damaged parts|confirm it is secure and watertight', 'Inspection found a loose or damaged structure.', 'A damaged canopy is a safety hazard.', LIFT),
  R('light-pole', /light pole|lamp post|pole base|\bpole\b/i, /lean|damag|rust|knock|down|loose|corrod|bent|fall|out|not work/i, 'repair', 'secure the area|inspect the base, bolts and wiring|repair or replace the damaged parts|re-secure the pole and confirm it is stable and the light works', 'Inspection found a damaged pole base or failed wiring.', 'A damaged pole is a safety hazard and the area may be unlit.', { invest: true, ...LIFT }),
  R('traffic-sign-sharp', /stop sign|traffic sign|street sign|parking sign|speed (limit )?sign|yield sign|one[- ]?way sign|do not enter|no parking sign|(handicap|ada|accessible|reserved) (parking )?sign|regulatory sign|sign ?post|sign pole|stop post/i, /\brip|\btear|\btorn|sharp|jagged|razor|laceration|\bcut\b|cuts?\b|slice|edge/i, 'replace', 'secure the area|keep people away from the sign|remove the torn or sharp sign face safely using cut-resistant gloves|replace it with a new compliant reflective sign face|cover any sharp edges left on the post or mounting hardware|confirm the sign is secure, upright and safe to touch', 'Inspection found a torn sign with a sharp, jagged edge.', 'The torn sign has a sharp edge that can cut or injure someone, so it needs to be fixed promptly.', { invest: true, hazard: true }),
  R('traffic-sign', /stop sign|traffic sign|street sign|parking sign|speed (limit )?sign|yield sign|one[- ]?way sign|do not enter|no parking sign|(handicap|ada|accessible|reserved) (parking )?sign|regulatory sign|sign ?post|sign pole|stop post/i, /bent|lean|tilt|crooked|down\b|knock|fall|fell|fade|faded|hard to read|illegible|damag|missing|stolen|broke|crack|rust|loose|twist|spin|graffiti|vandal|hit|struck|dent|peel|worn/i, 'repair', 'secure the area around the sign|straighten the sign post|re-anchor the post in the ground or replace a bent or damaged post|replace a faded, damaged or missing sign face with a compliant reflective sign|confirm the sign is upright, secure and clearly visible to drivers', 'Inspection found a leaning, bent, faded or damaged traffic sign.', 'A damaged or hard-to-read stop or traffic sign is a safety hazard for drivers and pedestrians.', { invest: true }),
  R('gutter-damage', /gutter|downspout|rain ?spout/i, /damag|loose|hang|sag|leak|rust|broke|detach|fall|pull|bent|crack|separat|dent|missing/i, 'repair', 'secure the area below the gutter|re-hang or replace the damaged sections and seal the joints|adjust the slope for proper drainage|flush the gutter with water and confirm there are no leaks', 'Inspection found a loose, sagging or damaged gutter.', 'A damaged gutter can let water run down the wall and damage the foundation.', LIFT),
  R('striping', /striping|stripe|parking lines|paint lines|stall lines|crosswalk|(handicap|ada|accessible) (stall|space|sign|parking)|arrows|re-?stripe/i, null, 'restripe', 'sweep and clean the pavement|mask and lay out the lines to specification|apply traffic paint evenly|let it dry|remove the masking', 'Inspection found faded parking and traffic markings.', 'Faded markings affect safety, traffic flow and accessibility compliance.', { crew: 2 }),
  R('asphalt-crack', /asphalt|blacktop|paving|pavement|parking lot/i, /crack|alligator|raveling|depress|settl|seal|deteriorat|worn|fad/i, 'seal', 'clean and blow out the cracks|apply crack filler or sealant|compact and sand as required|let it cure|return the area to traffic', 'Inspection found cracked and weathered pavement.', 'Cracks let in water that makes damage worse and shortens pavement life.', { crew: 2, no: /pothole|hole/i }),
  R('curb-bollard', /curb|bumper block|wheel stop|bollard|parking block/i, /damag|broke|crack|loose|missing|knock|fall|bent|spall/i, 'repair', 'remove the damaged unit|re-anchor or replace it|secure it level and plumb|clean up the area', 'Inspection found a damaged or loose unit.', 'Damaged curbs and bollards are a trip and vehicle hazard.', { crew: 2 }),
  R('catch-basin', /catch basin|storm drain|area drain|trench drain|yard drain|drain grate|storm sewer/i, /clog|block|back|flood|standing|overflow|sink|damag|missing|full|debris|slow/i, 'clear', 'remove the grate and the debris|flush or jet the line|inspect the structure|replace the grate and confirm water drains freely', 'Investigation found the drain blocked with debris.', 'Blocked drains cause flooding on the property.', { crew: 2 }),
  R('landscape', /landscap|\btrees?\b|shrub|bush|branch|\blimb\b|grass|lawn|weeds|mulch|overgrown|hedge/i, null, 'trim', 'trim or remove the overgrown or damaged vegetation|clear the sightlines, walkways and signage|haul away the debris|leave the area clean and neat', 'Inspection found overgrown or damaged vegetation.', 'Overgrown or damaged vegetation affects safety, security and curb appeal.', { crew: 2 }),
  R('snow-ice', /snow|icy|de-?ic|ice melt|ice (on|patch)|slippery|salt(ing)?/i, null, 'clear', 'clear the snow and ice from the walkways, entrances and parking areas|apply ice melt where needed|check the drains and entrances for hazards|confirm safe access', 'Inspection found snow and ice on the walking surfaces.', 'Snow and ice create a slip hazard for customers and staff.', { crew: 2 }),
  R('power-wash', /pressure wash|power wash|wash(ing)? (the )?(building|sidewalk|entrance|walkway|dumpster|canopy|exterior)|dirty (sidewalk|exterior|entrance)/i, null, 'pressure wash', 'sweep and prepare the area|apply cleaner to heavy stains|pressure wash the surface|rinse and leave the area clean', 'Inspection found a dirty or stained surface.', 'A dirty exterior looks unprofessional to customers.', { crew: 2 }),
  R('trash', /dumpster|trash|garbage|debris|litter|bulk waste|haul/i, null, 'remove', 'collect and bag the debris|haul it to proper disposal|sweep and clean the area|confirm the area is clear', 'Inspection found debris and trash that needed removal.', 'Trash and debris look unprofessional and can attract pests.', { no: /disposal/i }),
  R('pest', /\bpests?\b|rodent|\bmouse\b|\bmice\b|\brats?\b|roach|cockroach|\bants?\b|bed ?bugs?|\bbirds?\b|\bnests?\b|wasp|\bbees?\b|spider|termite|insect|droppings/i, null, 'treat', 'inspect for entry points and activity|set traps or apply an approved treatment|seal the entry points where possible|clean the affected area and schedule a follow-up', 'Inspection found signs of pest activity.', 'Pests are a health and sanitation concern.', { invest: true }),
  R('odor', /odor|smell|stink|stench/i, null, 'repair', 'trace the source of the odor|check the drains, traps and trash areas|clean or repair the source|confirm the odor is gone', 'Investigation traced the odor to a dry trap or a sanitation issue.', 'Odors affect customers and staff and can signal a plumbing or moisture problem.', { invest: true }),
  R('water-extract', /flood|puddle|wet (floor|carpet)|standing water|water (on|in) the floor|water everywhere|water damage/i, null, 'extract', 'stop the water source if possible|extract the standing water with a wet vacuum|set fans and dehumidifiers to dry the area|inspect for hidden moisture and confirm it is dry', 'Investigation found standing water from a leak or backup.', 'Standing water can damage finishes and lead to mold.', { invest: true, crew: 2, no: /roof|ponding|parking|catch basin|drain grate/i }),

  // ---------------- LIFE SAFETY ----------------
  R('extinguisher', /fire extinguisher|extinguisher/i, null, 'inspect', 'inspect the extinguisher for charge, pin, hose and damage|replace or recharge any that fail|update the inspection tag|confirm it is mounted and accessible', 'Inspection found an extinguisher needing service or a tag update.', 'Extinguishers must be inspected and ready for use for safety and code compliance.'),
  R('sprinkler', /sprinkler|fire suppression|standpipe|fire pump|fire riser|fire line/i, /leak|drip|damag|corrod|paint|trouble|valve|flow|broke|head|cover|low pressure/i, 'repair', 'isolate the zone using fire protection procedures|repair or replace the leaking head or valve|restore the system and notify the monitoring company|confirm there are no leaks and normal pressure', 'Investigation found a leaking or damaged head or valve.', 'The sprinkler system must be fully working to protect the building.', { invest: true }),
  R('emergency-equip', /eye ?wash|\baed\b|first aid|defibrillator|safety shower/i, null, 'inspect', 'inspect and test the unit|replace the expired supplies, batteries or pads|document the inspection|confirm it is accessible and ready', 'Inspection found expired supplies or a weak battery.', 'Emergency equipment must be ready when it is needed.'),
  R('egress', /exit (path|route)|egress|blocked exit|blocked door|obstruct/i, null, 'clear', 'clear the obstruction from the exit path|confirm the doors open fully|check the signage and lighting|confirm the route is clear and compliant', 'Inspection found the exit path blocked.', 'Exit paths must be clear for safe evacuation and code compliance.'),

  // ---------------- COUNTERS, FIXTURES & FURNITURE ----------------
  R('countertop', /counter ?top|countertop|teller (counter|line|station|pod)|laminate|formica|solid surface|marble top/i, /damag|chip|crack|loose|peel|delaminat|scratch|burn|stain|separat/i, 'repair', 'clean and prepare the damaged area|repair or replace the damaged laminate or section|secure the loose edges|confirm a smooth, safe surface', 'Inspection found damaged or peeling counter material.', 'A damaged counter looks unprofessional and can injure staff and customers.'),
  R('furniture-fix', /chair|desk|table|couch|sofa|bench|stool|credenza|bookcase|shelf|shelves|file cabinet/i, /broke|loose|wobbl|fall|crack|damag|stuck|jam|tear|rip|split|leg/i, 'repair', 'inspect the damaged joints and hardware|tighten, glue or replace the failed parts|reinforce the weak area|confirm the item is stable and safe to use', 'Inspection found loose joints or failed hardware.', 'A broken piece of furniture is unsafe and unusable.', { no: /lock|key/i }),
];

module.exports = { TRADES, toPast };
